services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    restart: unless-stopped
    ports:
      - "15000:5000"
    volumes:
      - ./data:/datastore
    environment:
      - PUID=1000   # ID пользователя (опционально)
      - PGID=1000   # ID группы (опционально)
