version: '3'
services:
  bytebase:
    image: bytebase/bytebase
    container_name: bytebase
    ports:
      - :8080
    environment:
      - DATABASE_URL=postgresql:password_ByteBase@192.168.1.38:5432/bytebase
    volumes:
      - ./bytebase-data:/data
    networks:
      - default_net

networks:
  default_net:
    external:
      true