all:
  hosts:
    master1:
      ansible_host: 192.168.1.66
      ip: 192.168.1.66
      access_ip: 192.168.1.66
    worker1:
      ansible_host: 192.168.1.61
      ip: 192.168.1.61
      access_ip: 192.168.1.61
    worker2:
      ansible_host: 192.168.1.39
      ip: 192.168.1.39
      access_ip: 192.168.1.39
  children:
    kube_control_plane:
      hosts:
        master1:
        worker1:
        worker2:
    kube_node:
      hosts:
        master1:
        worker1:
        worker2:
    etcd:
      hosts:
        master1:
        worker1:
        worker2:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
