version: "3"

services:

  traefik:
    image: "traefik:v3.1.4"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      # - "--api.insecure=true"
      # - "--providers.docker=true"
      # - "--providers.docker.exposedbydefault=false"
      # - "--entryPoints.web.address=:80"
      # - "--entryPoints.websecure.address=:443"
      # - "--providers.docker.tls.ca=/certs/rootCA.crt"
      # - "--providers.docker.tls.cert=/certs/traefik.homeleb.local.cert"
      # - "--providers.docker.tls.key=/certs/traefik.homeleb.local.key"
      - "--providers.file.directory=/config/dynamic"
      - "--providers.file.watch=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./certs:/certs"
      - "./config:/config"
      - "./config/static.yaml:/etc/traefik/traefik.yaml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik

networks:
  traefik: {}
