services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default_net

networks:
  default_net:
    external: true