services:
  healthcheck:
    container_name: healthcheck
    image: healthchecks/healthchecks:latest
    env_file:
        - .env
    ports:
        - 8000
        # To enable SMTP on port 2525, set SMTPD_PORT=2525 in .env
        # and uncomment the following line:
        # - "2525:2525"
    # command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uwsgi /opt/healthchecks/docker/uwsgi.ini'
    networks:
      - default_net

networks:
  default_net:
    external: true