services:
  linkwarden:
    container_name: linkwarden
    image: ghcr.io/linkwarden/linkwarden:latest # comment this line to build from source
    env_file: .env
    restart: always
    # build: . # uncomment this line to build from source
    ports:
      - 3000
    volumes:
      - ./data:/data/data
    networks:
      - default_net

networks:
  default_net:
    external: true